puretones_AC = {'experimenter':'wendy', 
'numTones':16,
'stimType':'Sine',
                     'minFreq':2000, 
                     'maxFreq':40000,
                     'minInt':70, 
                     'maxInt':70, 
                     'numInt':1, 
                     'soundLocation':'left', 
                     'stimDur':0.1, 
                     'isi':0.5}
