puretones_AC = {'experimenter':'wendy', 
                     'minFreq':2000, 
                     'maxFreq':40000, 
                     'numTones':60, 
                     'MinInt':70, 
                     'maxInt':70, 
                     'numInt':1, 
                     'soundLocation':'right', 
                     'stimDur':0.1, 
                     'isi':0.5}
