puretones_AC.1sec = {'experimenter':'wendy', 
                     'minFreq':2000, 
                     'maxFreq':40000, 
                     'numTones':60, 
                     'numTones':60, 
                     'MinInt':70, 
                     'maxInt':70, 
                     'numInt':1, 
